# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keven Jesus
email: falecom@keven.com.br
description: > # this means to ignore newlines until "baseurl:"
  Paulistano meio nordestino, fundador da maior comunidade de Bootstrap do Brasil, 
  professor e desenvolvedor Front-end especialista, apaixonado por tecnologias 
  Javascript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.keven.com.br" # the base hostname & protocol for your site
twitter_username: keven_jesus
github_username:  kevenjesus

# Build settings
markdown: kramdown
permalink: /:title
